options:
  bigtop_version:
    type: string
    default: '1.2.0'
    description: |
        Apache Bigtop release version. The default, '1.2.0' will use the
        current GA release, Bigtop 1.2.0, for all hiera data, puppet recipes,
        and installable packages. Set this to 'master' to use the latest
        upstream bits.
  install-cuda:
    type: boolean
    default: false
    description: |
      Install the CUDA binaries if capable hardware is present. This option
      is False by default, as not all applications support GPU acceleration.
